on:
  push:
    branches:
      - master

jobs:
  process:
    runs-on: ubuntu-latest
    name: Update Contributors List
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Update Contributors List
        uses: akhilmhdh/contributors-readme-action@v2.3.11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
