services:
  analytics:
    build: .
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017/bustinel
      GOOGLE_TRANSIT_FILE_URL: https://gtfs.adelaidemetro.com.au/v1/static/latest/google_transit.zip
      FEED_URL: https://gtfs.adelaidemetro.com.au/v1/realtime/vehicle_positions
      # CONTACT_EMAIL: Your email here, this must be set to receive complaints
      ENVIRONMENT: development
    restart: always
    networks:
      - development

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - bustinel-development-mongo:/data/db
    networks:
      - development

volumes:
  bustinel-development-mongo:

networks:
  development:
    driver: bridge
